//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainEgressPolicy) DeepCopyInto(out *DomainEgressPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainEgressPolicy.
func (in *DomainEgressPolicy) DeepCopy() *DomainEgressPolicy {
	if in == nil {
		return nil
	}
	out := new(DomainEgressPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainEgressPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainEgressPolicyList) DeepCopyInto(out *DomainEgressPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DomainEgressPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainEgressPolicyList.
func (in *DomainEgressPolicyList) DeepCopy() *DomainEgressPolicyList {
	if in == nil {
		return nil
	}
	out := new(DomainEgressPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainEgressPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainEgressPolicySpec) DeepCopyInto(out *DomainEgressPolicySpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	if in.DomainEgress != nil {
		in, out := &in.DomainEgress, &out.DomainEgress
		*out = make([]DomainEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainEgressPolicySpec.
func (in *DomainEgressPolicySpec) DeepCopy() *DomainEgressPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DomainEgressPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainEgressPolicyStatus) DeepCopyInto(out *DomainEgressPolicyStatus) {
	*out = *in
	if in.ResolvedDomains != nil {
		in, out := &in.ResolvedDomains, &out.ResolvedDomains
		*out = make([]ResolvedDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainEgressPolicyStatus.
func (in *DomainEgressPolicyStatus) DeepCopy() *DomainEgressPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DomainEgressPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainEgressRule) DeepCopyInto(out *DomainEgressRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]networkingv1.NetworkPolicyPort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainEgressRule.
func (in *DomainEgressRule) DeepCopy() *DomainEgressRule {
	if in == nil {
		return nil
	}
	out := new(DomainEgressRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedDomain) DeepCopyInto(out *ResolvedDomain) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.UpdateTimestamp.DeepCopyInto(&out.UpdateTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedDomain.
func (in *ResolvedDomain) DeepCopy() *ResolvedDomain {
	if in == nil {
		return nil
	}
	out := new(ResolvedDomain)
	in.DeepCopyInto(out)
	return out
}
