apiVersion: v1
kind: Service
metadata:
  name: {{ include "domain-egress-policy.name" . }}-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "domain-egress-policy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 53
      targetPort: 8053
      protocol: UDP
      name: dns
  selector:
    {{- include "domain-egress-policy.selectorLabels" . | nindent 4 }}
