apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "domain-egress-policy.fullname" . }}-validating-webhook-config
  {{- if .Values.admissionWebhooks.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-serving-cert" .Release.Namespace (include "domain-egress-policy.fullname" .) | quote }}
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "domain-egress-policy.fullname" . }}-webhook'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-policy-icefed-io-v1-domainegresspolicy
  failurePolicy: Fail
  name: vdomainegresspolicy.kb.io
  rules:
  - apiGroups:
    - policy.icefed.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - domainegresspolicies
  sideEffects: None
