apiVersion: v1
kind: Service
metadata:
  name: {{ include "domain-egress-policy.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "domain-egress-policy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: webhook
  selector:
    {{- include "domain-egress-policy.selectorLabels" . | nindent 4 }}
