---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policy-icefed-io-v1-domainegresspolicy
  failurePolicy: Fail
  name: vdomainegresspolicy.kb.io
  rules:
  - apiGroups:
    - policy.icefed.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - domainegresspolicies
  sideEffects: None
