# permissions for end users to edit domainegresspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: domain-egress-policy
    app.kubernetes.io/managed-by: kustomize
  name: domainegresspolicy-editor-role
rules:
- apiGroups:
  - policy.icefed.io
  resources:
  - domainegresspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.icefed.io
  resources:
  - domainegresspolicies/status
  verbs:
  - get
