---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - policy.icefed.io
  resources:
  - domainegresspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.icefed.io
  resources:
  - domainegresspolicies/finalizers
  verbs:
  - update
- apiGroups:
  - policy.icefed.io
  resources:
  - domainegresspolicies/status
  verbs:
  - get
  - patch
  - update
